str='computer'
str1="science"
str2='''department'''
print(str[1])
print(str[-1],str[-2],str[-3])
print(str2[1:5])
print(str2[1:-1])
print(str2[:6])
print(str2[1:])
print(str2[:-1])
print(str2[-3:])
print(str2[::-1])
print(str2[::1])
print(str2[3::])
str3="".join(reversed(str2))
print(str3)
a="geeks for geeks"
l=list(a)
print(l)
l[10]='L'
b=a[:10]+'L'+a[11:]
print(b)
b=a[:10]+'L'+'i'+'f'+'e'
print(b)
a="".join(l)
print(a)
c="".join(reversed(l))
print(c)
c="".join(reversed(a))
print(c)
str="{},{},{}".format('geeks', 'for', 'geeks')
print(str)
str1="{},{},{}".format('geeks','for','geeks')
print(str1)
str2="{1},{2},{0}".format('geeks','for','geeks')
print(str2)
str3="{a},{b},{c}".format(a='geeks',b='for',c='geeks')
print(str3)
